language: python

sudo: required
services:
  - docker

env:
  matrix:
    - DISTRO_TO_BUILD=centos-7
    - DISTRO_TO_BUILD=debian-8
    - DISTRO_TO_BUILD=debian-9
    - DISTRO_TO_BUILD=fedora-24
    - DISTRO_TO_BUILD=fedora-25
    - DISTRO_TO_BUILD=fedora-26
    - DISTRO_TO_BUILD=fedora-27
    - DISTRO_TO_BUILD=opensuse-42.2
    - DISTRO_TO_BUILD=opensuse-42.3
    - DISTRO_TO_BUILD=ubuntu-14.04
    - DISTRO_TO_BUILD=ubuntu-16.04
    - DISTRO_TO_BUILD=ubuntu-17.10

  global:
    - REPO=crops/yocto
    - secure: "2KlvoO//Y91Du8/DM7c59TSPS9NIDhrdPqz9wPSPmC23Zj9W6o8yTOl7fxIle5gnOcREr8q9v3dxmLHvFb7Q+HFOMqoXZKGrFwzdJI2H9GVVClCjF9MWETLZ3aRSTDi61Dcaps/bk3S2sDD9/zgugh3fBsUj0RawH4Oh3NAvP+FOk4eNg3wM0cizshuZ3/PsOYbWI568JPxSQx4j8V/RPgY7IaXz6dPuYQ9P8bMDnjdMmYr+kqsG0GPkgruYnSOOrYjDDft8y5Vgj8YUQzgMItmAPvCmQUlZXIhOT5qloutPfD+WyqV2bm7Kcn8+z1szChhv3GBUcLSp69Hhm93nrbgGEVNc7L/ncgBmHRqfIA/7xVNrKp05q3AmRR6USfsdY0yHCY2t1dNt1nKp02hkRIUGErot5epEDN5peQiLxbnXJt8GKLXAbb1D23BDqQkzhi4890z8o3+2YSLbXP66XD5PKRMlRlLFBfv2AnhHN4bUXCChEy2kkzmbw4YlW0bIwFMIqaQjmSMGYFyfmdiERXKD2opBly4fWFROBpN7t99on7y+XAwihW1ph2ZPL+bplUEs0YeL8irla7cMg/tXzixgjF0jDzpm+XrEJVDgNG/Tn9U5DibfdrNdx9AfkQwI+zVJSdxMvSEoViQwdrzrH9pHR/NJWbNrPPmGC2LDTKQ="
    - secure: "ms9Lqkx31BUxYFREus5b4P8Hw0Yy13pwsfbbJ5ZE/PYpj5zJWD3Cl1vLbphTFwXXh3C3V847w9hPQUuw2VF7POvOpIifKI4FaUzjGF5xYJ75nNNETGKz8aGicsj0gCsSLTxYRZxfZ7xm0Y8uO6YLgHVnI8BrK9g5RGXEoOkKwqKSoMWJRrIsL3F+QJcL7AnTtHclI1QIP+dDDegEXQy0W+OBvzD6L9QDL1bzJYGyyKZ0s5flPQAQK86adjNw0Z7ln06xhr8nsgkW/kJ1zHor4g3fMulBh5El7MdZXpR6GIcDdqVhcCCHgxgWs3LwU3Msy422VrPjN9T5iu/NXNz02jzHpqq+3XVyZB1f2LEihrFlSxFTIV6qzPNP/CEwMllcDtZzpMMbg3EMkVttrgc8YgilURnf4gvelTbOemtJX6NsgHz3uh9L2g5YzLt8bdGCVtmUPci3leg9HnsxROo2BBGKbvMzL2fpyv47QM2FtryRdzWAOHscOKVAygu0YcpnDftlIY90SyeSpECUfKzPmw4xuZIuQmJaKMtXQqnUslACYfpyV0zqw48ef+GGj8YDeEzWaqQRfKUFq7dE9q7bsDEAPy9IohSAvKgt6VpjXScOk7prYD11mWjGIDe+/SSKW7DDr+MbbqLz3CrsgRqlvlk2E5UVTWN/sA6VpcWUu9s="
    - secure: "nwd7t4bDLw+PnVzxj+O8R8AbAIy3LiF1pT4MfmeQEskmBG01jiHhR1hcJBmAD9BF2PiAM04h80pNzv6IGzvDyqLrHuEf+91i/cwvmjTgdP//gnwADRK0u2NTYic9rM1gz1YcFCf3GegoRCKZBhW7YSv8uJHUMllTsDpGuXGL+ytmqUEndPzPfXigAN6PWf+/GD7KP1q/o3zvlJZtCFdYCs+EkthlUbMaZwPj7PU/L9EUCPGib2LOK3SvSZQejZUZrXg2ftme2CYpuRp3xw/5bOjpagThLQCDOJQvZLKoTEzCtt4RBvuF+HFTtepwRY2wRjG6tbujXerbrZLsi/I0HTrg+jBjpSDIbWtv7CFSYTBrZyHrFflOpyXBEDK+75bB8v6qR9QPN0hpz8maLq14m7MOffKMhTM/S3N8KTWvLJIxbDeHaNCJWUzW54B3YFVEUezE4f/pjmSbL+Zwu8/C+zC2i0tdpAB04TnLUCx6xHF4nbjMu23BBb/hbn//SvuAT8OVhIrC2JXEw59BLYzp+1amB5+d1AKF9CaInn/Lruno0a6C5sjWTBDqx6ZXwTtRIywm+tgGq0bS44vNkRFme+iQEVFNY0cLuvCjqP50SEUmyJB5y4rUO6bCXZvqXIjnGAIUGp3if5GbMZ9Z1y9a+1Mu3l4P0WiGuo60CtvH2+4="

before_install:
  # upgrade docker-engine to specific version
  - pip install pytest-pep8

script:
  - py.test -ra --pep8
  - ./build_container.sh

after_success:
  - ./deploy.sh
