language: python

sudo: required
services:
  - docker

env:
  matrix:
    - DISTRO_TO_BUILD=centos-7
    - DISTRO_TO_BUILD=debian-9
    - DISTRO_TO_BUILD=debian-10
    - DISTRO_TO_BUILD=fedora-28
    - DISTRO_TO_BUILD=fedora-29
    - DISTRO_TO_BUILD=fedora-30
    - DISTRO_TO_BUILD=opensuse-15.0
    - DISTRO_TO_BUILD=opensuse-15.1
    - DISTRO_TO_BUILD=ubuntu-14.04
    - DISTRO_TO_BUILD=ubuntu-16.04
    - DISTRO_TO_BUILD=ubuntu-18.04
    - DISTRO_TO_BUILD=ubuntu-19.04

  global:
    - REPO=crops/yocto
    - secure: "z67VeChlGVgLNRAyZxtQUrk9nXaOMGrh9XeqG4tG/55T2SNbse8ZTAbjTV0WhUQrbPYByusTEpRKJ/v4t1ugmUZ9FIAPQREWAuTmXYXVrjkjhqXQfExIMT9GAspoNvBzS0GwrHOc+8GA0C+N9qfp6TAceHy3BtYlI1YrdP2bQO77P8DTtoVyCayBJqY1AcHhrOe+FvodBtbitqCF6djL1yIN27J8ws3BcyE6PkgyKcaH1gnQuzbhTfKhLV+LggFQnSY81+aONyHhYpkbCPly0l1wo4SeE4UA1xwwAdB3N4yRRuoFs/fIVLE4mmMraRI/S70iShFJtIdYlLhkDCc/zA1mmAQjxG/ZLuVJ1Pp83wqrYep7rSj+1VqPQnlyRqJFyZU/C41FFsmJrFxqXqjvSjBie38VdCQ+cnW3wLodhHC7iorR8rcFZ4quNc2yWrVKHxND0GVP3tG75KESHBWnjccx9YhCJHUH6tUjf1EYIZLJ2GZerZHva4bukctImZEvvBxu+I8uUWoGzpx5p5KR1drd74lsGSTukwo8Fugx1ba2ltEGDEXf8bantPD8s8FZNlQFRCP3w7ZZkIp5YBRpcVNZ7FIxQa3t8dhWDWWQ4NBrH/xTP1b5/a8hnoPnAMGGRCl2cUuX/s03AIGQe6fFhfBY5u/BVXJWqiZ6NB+ApK8="
    - secure: "pEvK42hX2ldDCmJ6crKZ9uCH6eELVuqB8kHgWeSD9s6qhg3hyuZ8Ot24cOFb+HetgfopTRmDxh6VlTBTFwWy5KYTkvoBycZjiI3KTdWe0HWC3aVp+Y+5JJ2tQ/1NNPoqkHaAcGsPbtX6kl17KOWxWn5awpIJw9ODp4bMf86vQoRSIwxU4KBii48Vx25xJLUn3z3g+me3ZEIoljBwZffWADy8lSY4bfaCzrjEo8jlq3UZ2QX46yb8LQ3mvDcB6aGi4XbND45TLZ5GTwhDZ+xYXf04bdRay84qpCBHpH18YaHdgAbniSH4o+PvJFkl0Fv8uA8cp19b+1TiI2Tt8IQo0dvpSnGFGbd9D6yFm/Dt91IySFLExu14yTP1l+skThpzHNl8vEL4OAAVpPbjne3NUA117RN8dSSIimXGYfkmC/4d2wlceW/FJ0C8WBNxywXSAkTFfx+zXDoi9orFylzLIBLVJBa8hSm7EW/EV2fAhjYGSH1/Ft7es2pSw2FunWWAYQiy4nRl/2RVkjdeW7eY49NtZlo6cbnl0yAljKvSxxh/yVOsd34DQsnE5CznvFu6sQLObd3AqNwYoZ4+YjU0KVWzIugulB0jedAOGUuZRqAtlq/jtiBeC8Ll+12Ej/aD6ILIks4gc8rIK74J+n+RCzXAnvjJ/rn5QQU56pmUgbo="

before_install:
  # upgrade docker-engine to specific version
  - pip install pytest-pep8

script:
  - py.test -ra --pep8
  - ./build_container.sh

after_success:
  - ./deploy.sh
