#!/usr/bin/env python

# bitbake.py
#
# Copyright (C) 2016 Intel Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# This is for testing the signal forwarding of run_bitbake. It just waits for
# a signal and then outputs a message telling what signal it received.

import os
import signal
import sys
import time

def handler(signum, frame):
    print('Handler called with signal {}'.format(signum))
    sys.stdout.flush()
    sys.exit(0)

# Set the signal handler
signal.signal(signal.SIGTERM, handler)
signal.signal(signal.SIGINT, handler)

print('Waiting for signal')
sys.stdout.flush()
time.sleep(10)
sys.exit(1)
