#!/usr/bin/env python3

# bitbake.py
#
# Copyright (C) 2016-2021 Intel Corporation
#
# SPDX-License-Identifier: GPL-2.0-only
#
# This is for testing the signal forwarding of run_bitbake. It just waits for
# a signal and then outputs a message telling what signal it received.

import os
import signal
import sys
import time

def handler(signum, frame):
    print('Handler called with signal {}'.format(signum))
    sys.stdout.flush()
    sys.exit(0)

# Set the signal handler
signal.signal(signal.SIGTERM, handler)
signal.signal(signal.SIGINT, handler)

print('Waiting for signal')
sys.stdout.flush()
time.sleep(10)
sys.exit(1)
