name: yocto-container build and test
on:
  push:
    branches:
      - master
  pull_request:

  # Allow for manually running
  workflow_dispatch:

  # Run at 00:52 UTC every Saturday
  schedule:
    - cron: '52 0 * * 6'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        distro_to_build: [
          alma-8,
          alma-9,
          centos-7,
          debian-10,
          debian-11,
          fedora-36,
          opensuse-15.4,
          ubuntu-18.04,
          ubuntu-20.04,
          ubuntu-22.04
        ]
        targetplatform: [
          linux/amd64
        ]
    env:
      DISTRO_TO_BUILD: ${{ matrix.distro_to_build }}
      TARGETPLATFORM: ${{ matrix.targetplatform }}
      REPO: crops/yocto
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GHCR_USERNAME: ${{ github.actor }}
      GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and test the images
      - name: Run build-and-test.sh
        run: ./buildx_container.sh

      # Deploy the images
      - name: Deploy
        run: ./deploy.sh
