name: yocto-container build and test
on:
  push:
    branches:
      - master
  pull_request:

  # Allow for manually running
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro_to_build: [
          centos-7,
          centos-8,
          debian-9,
          debian-10,
          fedora-33,
          fedora-34,
          opensuse-15.2,
          ubuntu-16.04,
          ubuntu-18.04,
          ubuntu-20.04
        ]
    env:
      DISTRO_TO_BUILD: ${{ matrix.distro_to_build }}
      REPO: crops/yocto
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      # Build and test the images
      - name: Run build-and-test.sh
        run: ./build_container.sh

      # Deploy the images
      - name: Deploy
        run: ./deploy.sh
